### ISSUE TITLE
app not working

### ISSUE THREAD

**Issue by sagarchoudhary96** [karadkar/Veggie#1]
Hey, i tried to run this app using the steps mentioned but there are lots of error. It would be great if you can update it

**Comment by karadkar** [comment]
hey @sagarchoudhary96 thanks for checking out
I'm no longer maintaining this project. I haven't been able to migrate old `Firebase` project to the new `Google Firebase` project.
Sorry for the inconvenience this may have caused to you. 
I'll update the Readme.
