### ISSUE TITLE
Registring user info

### ISSUE THREAD

**Issue by RPrithvi007** [karadkar/Veggie#2]
@karadkar hii i'm trying to open your project. when run this code showing the pop failed to register  Error_Registering_userinfo  i'm trying more and more time but i can't solved this problem.
can u tell me how to solved this problem and not generating the key of your project  
u can also check images in below 
![userinfo](https://user-images.githubusercontent.com/48403097/56296624-80edfd00-614c-11e9-8790-b3e30c9a4e2f.jpeg)

**Comment by karadkar** [comment]
hey @RPrithvi007 thanks for checking out
I'm no longer maintaining this project. I haven't been able to migrate old `Firebase` project to the new `Google Firebase` project.
Sorry for the inconvenience this may have caused to you. 
I'll update the Readme.

**Comment by RPrithvi007** [comment]
It's k Sir No Problem
sorry if u can mail me ur project after updating

**Comment by rohitkaradkar** [comment]
@RPrithvi007 I do not plan to update this project.
